In [1]:
from helper import *
import numpy as np
from Simulation.ForwardKinematics import ForwardKinematics
from Simulation.InverseKinematics import InverseKinematics
fk = ForwardKinematics() 
ik = InverseKinematics()

q_target = np.array([0.0, 0.0, 0.0, np.pi*0.5, 0.0, -np.pi*0.5, 0.0])
q_guess  = np.array([np.pi*0.1, 0.0, 0.0, np.pi*0.5, 0.0, -np.pi*0.5, -np.pi*0.6])
x_target = fk.getFK(q_target)
q_sol_classic, error_norm_classic, success_classic = ik.getIK_classic_body(x_target, q_guess, 0.001)

print(success_classic)

True


In [2]:
import numpy as np


q_target = np.array([0.0, 0.0, 0.0, np.pi*0.5, 0.0, -np.pi*0.5, 0.0])
q_guess  = np.array([np.pi*0.1, 0.0, 0.0, np.pi*0.5, 0.0, -np.pi*0.2, -np.pi*0.6])
x_target = fk.getFK(q_target)
x_act = fk.getFK(q_guess)

T_target = x_target.asTransformation()
T_act = x_act.asTransformation()

delta_x = x_target*x_act.inverse()
log_error = 2.0*delta_x.log().as6Vector().flatten()
        
dT_space = T_target@ik.inverse_transformation_matrix(T_act)
#dT_body = ik.inverse_transformation_matrix(T_act)@T_target

print(dT_space)
print(ik.matrix_logarithm(dT_space))
q_sol_classic, error_norm_classic, success_classic = ik.getIK_classic_space(x_target, q_guess, 0.001)

[[   0.121   -0.961    0.250    0.543]
 [   0.627   -0.121   -0.769    0.484]
 [   0.769    0.250    0.588   -0.097]
 [   0.000    0.000    0.000    1.000]]
[   0.926   -0.472    1.443    0.729   -0.093   -0.405]
[[   0.000   -0.309    0.000   -0.309    0.951   -0.309    0.769]
 [   0.000    0.951    0.000    0.951    0.309    0.951    0.250]
 [   1.000    0.000    1.000    0.000    0.000    0.000    0.588]
 [   0.000   -0.417    0.000   -1.082   -0.352   -1.082   -0.157]
 [   0.000   -0.135    0.000   -0.352    1.082   -0.352    0.484]
 [   0.000    0.000    0.000    0.000    0.000    0.700   -0.000]]
[   0.926   -0.472    1.443    0.729   -0.093   -0.405]
1.966438557475829
[[  -0.743   -0.241    0.497   -0.211    0.649   -0.000]
 [  -0.496    1.528   -0.000    1.338    0.435   -0.009]
 [  -0.743   -0.241    0.497   -0.211    0.649   -0.000]
 [   0.189   -0.580   -0.000   -1.338   -0.435   -1.410]
 [  -1.115   -0.362   -0.005   -0.587    1.807   -0.000]
 [   0.001   -0.002   -0.000   