In [1]:
from Simulation.QP_DifferentialKinematicsAcc import QP_DifferentialKinematicsAcc
import numpy as np

np.set_printoptions(precision=2, suppress=True, linewidth=200, formatter={'float': '{:8.3f}'.format})

qp_idk = QP_DifferentialKinematicsAcc(verbose = True)

Weighting matrix P:
[[   5.500    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    5.500    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    0.000   11.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    0.000    0.000    0.550    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    0.000    0.000    0.000    0.550    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    0.000    0.000    0.000    0.000    0.550    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    0.000    0.000    0.000    0.000    0.000    0.550    0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000]
 [   0.000    